// Mocks generated by Mockito 5.4.4 from annotations
// in madmudmobile/test/blocs/products_bloc/products_repository_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:cloud_firestore/cloud_firestore.dart' as _i8;
import 'package:madmudmobile/features/products/domain/models/category/category.dart'
    as _i4;
import 'package:madmudmobile/features/products/domain/models/collection/collection.dart'
    as _i3;
import 'package:madmudmobile/features/products/domain/models/design/design.dart'
    as _i5;
import 'package:madmudmobile/features/products/domain/models/piece/piece.dart'
    as _i9;
import 'package:madmudmobile/features/products/domain/models/products/products.dart'
    as _i2;
import 'package:madmudmobile/features/products/repository/products_repository.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProducts_0 extends _i1.SmartFake implements _i2.Products {
  _FakeProducts_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollection_1 extends _i1.SmartFake implements _i3.Collection {
  _FakeCollection_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategory_2 extends _i1.SmartFake implements _i4.Category {
  _FakeCategory_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDesign_3 extends _i1.SmartFake implements _i5.Design {
  _FakeDesign_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRepository extends _i1.Mock
    implements _i6.ProductsRepository {
  @override
  _i7.Future<_i2.Products> fetchProductData() => (super.noSuchMethod(
        Invocation.method(
          #fetchProductData,
          [],
        ),
        returnValue: _i7.Future<_i2.Products>.value(_FakeProducts_0(
          this,
          Invocation.method(
            #fetchProductData,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Products>.value(_FakeProducts_0(
          this,
          Invocation.method(
            #fetchProductData,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Products>);

  @override
  _i7.Future<_i2.Products> fetchAllProductDataFromCloud() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllProductDataFromCloud,
          [],
        ),
        returnValue: _i7.Future<_i2.Products>.value(_FakeProducts_0(
          this,
          Invocation.method(
            #fetchAllProductDataFromCloud,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i7.Future<_i2.Products>.value(_FakeProducts_0(
          this,
          Invocation.method(
            #fetchAllProductDataFromCloud,
            [],
          ),
        )),
      ) as _i7.Future<_i2.Products>);

  @override
  _i3.Collection toCollection(_i8.QueryDocumentSnapshot<Object?>? doc) =>
      (super.noSuchMethod(
        Invocation.method(
          #toCollection,
          [doc],
        ),
        returnValue: _FakeCollection_1(
          this,
          Invocation.method(
            #toCollection,
            [doc],
          ),
        ),
        returnValueForMissingStub: _FakeCollection_1(
          this,
          Invocation.method(
            #toCollection,
            [doc],
          ),
        ),
      ) as _i3.Collection);

  @override
  _i4.Category toCategory(_i8.QueryDocumentSnapshot<Object?>? doc) =>
      (super.noSuchMethod(
        Invocation.method(
          #toCategory,
          [doc],
        ),
        returnValue: _FakeCategory_2(
          this,
          Invocation.method(
            #toCategory,
            [doc],
          ),
        ),
        returnValueForMissingStub: _FakeCategory_2(
          this,
          Invocation.method(
            #toCategory,
            [doc],
          ),
        ),
      ) as _i4.Category);

  @override
  _i5.Design toDesign(
    _i8.QueryDocumentSnapshot<Object?>? doc,
    List<_i4.Category>? categories,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toDesign,
          [
            doc,
            categories,
          ],
        ),
        returnValue: _FakeDesign_3(
          this,
          Invocation.method(
            #toDesign,
            [
              doc,
              categories,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeDesign_3(
          this,
          Invocation.method(
            #toDesign,
            [
              doc,
              categories,
            ],
          ),
        ),
      ) as _i5.Design);

  @override
  _i9.Piece? toPiece(
    _i8.QueryDocumentSnapshot<Object?>? doc,
    List<_i5.Design>? designs,
    List<_i3.Collection>? collections,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toPiece,
          [
            doc,
            designs,
            collections,
          ],
        ),
        returnValueForMissingStub: null,
      ) as _i9.Piece?);
}
